### ISSUE TITLE
Dependency Issue on Windows

### ISSUE THREAD

**Issue by mco78** [Spandan-Madan/DeepLearningProject#17]
Tried to setup with the .yml file which was aborted.
Manual installation of the requested packages led to an error: tensorflow on Windows is only supported in 64-bit Python 3.5. Updating python raises depency errors for functools32 and subprocess32, which only run with Python 2.7.
So based on my limited knowledge: there is no way of setting up the environment on Windows. Or am I missing something?

**Comment by Spandan-Madan** [comment]
Hi, 

It can be set up on a windows machine. Tensorflow on all platforms - windows, unix and mac is supported on only Python 3.5. So, if your machine has python 3.6 it will not work. 

Could you tell which specific package were you installing when you got this error?

**Comment by mco78** [comment]
I guess the problem is, that imdbpy is not compatible with Python 3.x. See here: 
[https://github.com/alberanid/imdbpy/issues/27](url)
But for Tensorflow to work under Windows, Python 3.5 is needed. So I can't use them together in one environment. 
But I solved this by creating two environments, one for the data gathering and one for the deep learning part, which works fine for me. Sorry, I'm really not an expert in Python and its package management, so maybe I just dont get how to do the installation process right... Feel free to delete the issue. Thanks anyway for the great tutorial!

**Comment by Spandan-Madan** [comment]
Makes sense. I suggest working with python 2.7 as it was all tested on it. Thanks for informing, let me add it to to repo :)

**Comment by Spandan-Madan** [comment]
@mco78 Added a clarification to README mentioning that Python 2.7 is required. Thanks for notifying! Glad it helped you out :)

**Comment by mco78** [comment]
Thank you, good job!
