### ISSUE TITLE
Varibles undefined when run the scripts

### ISSUE THREAD

**Issue by coky** [Spandan-Madan/DeepLearningProject#28]
In section 7, when extract VGG features for scraped images.
In the for loop where try and except block located, the varible 'imname' was not declared, may be change like the following:

    for mov in poster_movies:
        i+=1
        mov_name=mov['original_title']
        mov_name1=mov_name.replace(':','/')
        poster_name=mov_name.replace(' ','_')+'.jpg'
        if poster_name in imnames:
            img_path=poster_folder+poster_name
            try:
                img = image.load_img(img_path, target_size=(224, 224))
                succesful_files.append(imname) # **imname undefined , change to poster_name ?**
                x = image.img_to_array(img)
                x = np.expand_dims(x, axis=0)
                x = preprocess_input(x)
                features = model.predict(x)
                file_order.append(img_path)
                feature_list.append(features)
                genre_list.append(mov['genre_ids'])
                if np.max(np.asarray(feature_list))==0.0:
                    print('problematic',i)
                if i%250==0 or i==1:
                   print "Working on Image : ",i
            except Exception,e:
                print Exception,":",e   # **for debuging**
                failed_files.append(imname) # **imname undefined , change to poster_name ?**
                continue
        else:
            continue

**Comment by AnshulBasia** [comment]
This has been fixed in newer versions, it is 'poster_name' now instead of 'imname'. Let me know if you have any doubts :)
