### ISSUE TITLE
TMDB Genre list() changed to movie_list()

### ISSUE THREAD

**Issue by magnusbil** [Spandan-Madan/DeepLearningProject#31]
In Section 3 when looking at returning Genres from TMDB the instructions state to use the .list() method of the Genre object returned by tmdb.Genres(). 

There has been an update to the API and list() no longer exists. There are separate lists for movies, tv, etc. Currently the function we're looking for is movie_list(), which returns the list of movie genres.

**Comment by Spandan-Madan** [comment]
Responded on the pull request conversation. As this issue doesn't require discussion between multiple people, we can take it up there in the PR conversation. Closing the issue here :)
