### ISSUE TITLE
Finding words that are most predictive of a genre

### ISSUE THREAD

**Issue by sachinsridhar** [Spandan-Madan/DeepLearningProject#36]
Hi, This was an extremely useful document, and I learnt a lot from the tutorial. An interesting extension to the problem would be to identify the words in the synopses that most distinguish a genre from other genres in the model - I have an analogous task in my project.

Is there a way to find the words that are most predictive of a genre? For example, is there a way to identify that the words ‘battle’, ‘challenge’ and ‘fight’ (for example) are the most predictive of a movie falling into the ‘Action’ category, based on the model we trained? i.e. which are the words (in the synopsis) that most prominently indicate that the synopsis would fall under a particular genre? (Using the model we have fit).
This basically translates to decoding the algorithm to find out how it works “under the hood.” - what features (words?) it uses "under the hood" to classify a synopsis into a genre. 

A solution I found online is in the code snippet below - Using the classifier coefficients from clf.coef_ (clf is the name of the model I fit) and picking the top 10 words (which the model uses to distinguish/identify a genre based on a given text). 

def print_top10(vectorizer, clf, class_labels):
    """Prints features with the highest coefficient values, per class"""
    feature_names = vectorizer.get_feature_names()
    for i, class_label in enumerate(class_labels):
        top10 = np.argsort(clf.coef_[i])[-10:]
        print("%s: %s" % (class_label,
              " ".join(feature_names[j] for j in top10)))

Please let me know if this is appropriate and if there is a better way of doing this.

**Comment by Spandan-Madan** [comment]
Hi Sachin,

That's a nice problem! I think that the proposed solution will work for an SVM, but not for a deep model which is expected.

For the deep model there's some ways I can think of in which you could "try" to get the words. For example :- 

1. Find samples that the model thinks are action with high probability (say 0.9 threshold or something), then compare it to samples the model does not think of as action. Compare the distribution of words in the two categories to find which ones are "action triggering" so to say.

2. Another way is to, for each sample, generate different versions by dropping 1 or 2 words and then seeing how the network's predictions change. As it is a model which takes a mean over all word's word2vec representation, it's basically a bag of words. If a word is an "action trigger" word, deleting it from the bag should reduce the network's confidence in thinking that the bag corresponds to the genre Action. 

Other ways can be thought of but these would be good starting points.

**Comment by Spandan-Madan** [comment]
@sachinsridhar  Were you able to make any progress on this front? Let me know if you need any help!
