### ISSUE TITLE
'Genres' object has no attribute 'list'

### ISSUE THREAD

**Issue by Major-Hawk** [Spandan-Madan/DeepLearningProject#40]
I get this error while compiling the code cell 15 of the notebook.

**Comment by Spandan-Madan** [comment]
Are you on the newly committed version or the previous one? Basically, when did you clone it?

A new pull request was updated just today and I am wondering if the code was broken before or did it break now.

**Comment by Major-Hawk** [comment]
I am on the latest commit.
The code must have broken after the pull request.

**Comment by Major-Hawk** [comment]
Change genres.list() to genres.movie_list().
This issue has been mentioned before but has not been fixed.

**Comment by Spandan-Madan** [comment]
Could you please make it runnable and create a PR with no merge conflicts please?

I can accept the PR once it's made.

Thanks!
