### ISSUE TITLE
404 for figure 1

### ISSUE THREAD

**Issue by golergka** [Spandan-Madan/DeepLearningProject#43]
The link to the figure 1: https://spandan-madan.github.io/DeepLearningProject/docs/contour.png seems to be incorrect

**Comment by Spandan-Madan** [comment]
Yea, the file was originally outside the folder and so relative paths got messed up. Could you please update the path to the image correcting the relative path and add a PR?

Thanks a lot!

**Comment by AnshulBasia** [comment]
Thanks @golergka  It can now be accessed at 'https://spandan-madan.github.io/DeepLearningProject/contour.png'.
