### ISSUE TITLE
"That" vs "Which" grammatical error. 

### ISSUE THREAD

**Issue by sriram-srinivasan** [Spandan-Madan/DeepLearningProject#44]
Kudos on a very well done writeup.  I have a simple grammatical correction ... in many cases, you have used 'which' in place of 'that'. 

See http://www.writersdigest.com/online-editor/which-vs-that

If 'which' is used to describe something, and is not preceded by a comma, it is a likely candidate for the confusion. 

For example, 
'use the available data to learn a function which can' ==> 'use the available data to learn a function that can'

**Comment by Spandan-Madan** [comment]
Hi Sriram, 

Glad you liked the tutorial! I will keep this in mind in future tutorials. 

Best,
Spandan
