### ISSUE TITLE
Example binarized vector representation is syntactically incorrect

### ISSUE THREAD

**Issue by ZeroCool2u** [Spandan-Madan/DeepLearningProject#45]
> Now let's store the genre's for these movies in a list that we will later transform into a binarized vector.
> 
> Binarized vector representation is a very common and important way data is stored/represented in ML. Essentially, it's a way to reduce a categorical variable with n possible values to n binary indicator variables. What does that mean? For example, let [(1,3),(4)] be the list saying that sample A has two labels 1 and 3, and sample B has one label 4. For every sample, for every possible label, the representation is simply 1 if it has that label, and 0 if it doesn't have that label. So the binarized version of the above list will be -
> 
```
> [(1,0,1,0]),
> (0,0,0,1])]
```

[This section](https://spandan-madan.github.io/DeepLearningProject/docs/Deep_Learning_Project-Pytorch.html#My-Implementation) has output that contains a brackets mismatch syntax error. Not a huge problem, but probably a bit confusing for a beginner. Otherwise, great tutorial!

**Comment by Spandan-Madan** [comment]
Thanks for pointing it out. We will get around to it in the next round of bug fixing hopefully!
