### ISSUE TITLE
TMDB API key

### ISSUE THREAD

**Issue by bwobst** [Spandan-Madan/DeepLearningProject#46]
Great walkthrough!

One recommendation is to replace your actual TMDB API key with a placeholder. That way no one can abuse your account via your API key.

P.S. Super nitpicky, but in that same block, I think the Jupyter step should read `In [5]:`

**Comment by Spandan-Madan** [comment]
Thanks for pointing that out @bwobst!

@AnshulBasia I suggest deleting your TMDB account. Even if you change the version on github now, anyone can still access your key from previous commits. Also, act on this fast I would suggest.
