### ISSUE TITLE
Cut out warnings from imports due to numpy ufunc and dtype sizes

### ISSUE THREAD

**Issue by scottstanie** [Spandan-Madan/DeepLearningProject#47]
Nice jobs with the notebooks- On block 2, if you'd like to get rid of the `RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88` warnings, the you can just add at the bottom of the block:

```python
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
```

**Comment by Spandan-Madan** [comment]
@AnshulBasia  This a great idea, you should do this.
