### ISSUE TITLE
appnope 0.1.0 not available on win-64 and linux channels. 

### ISSUE THREAD

**Issue by CptMacHammer** [Spandan-Madan/DeepLearningProject#6]
The appnope package is made to disable App Nap on OS X. If you are on a different platform you must remove or comment out the line.

**Comment by Spandan-Madan** [comment]
Hey, 

Where is this package being used? It's not listed in the dependencies or anywhere in the tutorial. if you search for the words "appnope" in the tutorial nothing shows up.

Can you link to the line number in the ipython notebook you are referring to?

**Comment by AnshulBasia** [comment]
Were you successful in building it on ubuntu or windows after removing that line ?

**Comment by AntonFriberg** [comment]
I was able to build it in a miniconda docker container after removing that line, yes! I am using Arch Linux on my host.
